package:
  name: smurff
  version: {{ environ.get("GIT_DESCRIBE_TAG", "0.99.9").lstrip("v") }}

source:
  path: ../..

build:
    number: {{ GIT_DESCRIBE_NUMBER }}
    ignore_run_exports:
      - llvm-openmp

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - llvm-openmp             # [osx]
  host:
    - llvm-openmp             # [osx]
    - intel-openmp
    - mkl-devel
    - eigen3
    - libboost
    - pybind11
    - highfive >=2.2
    - h5py
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - numpy
  run:
    - python {{ python }}
    - intel-openmp # [not win]
    - mkl
    - libboost # [not win]
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - hdf5
    - h5py
    - h5sparse-tensor >=0.2.2
  
test:
  requires:
    - parameterized
    - pytest
  source_files:
    - python/test/*.py

about:
  home: https://github.com/ExaScience/smurff
  license:  MIT
